name: DrakesMagic
version: '${project.version}'
main: com.drakescraft.suites.magic.DrakesMagicPlugin
api-version: '1.21'
author: DrakesCraft-Labs
description: Mega-Suite de Artes Arcanas, Alquimia, Reliquias Antiguas y Misticismo.
depend: [DrakesCore]
