name: DrakesServer
version: '${project.version}'
main: com.drakescraft.suites.server.DrakesServerPlugin
api-version: '1.21'
author: DrakesCraft-Labs
description: Mega-Suite de Servidor y Gameplay Standalone: Motor Odysseia, Economia y Social.
depend: [DrakesCore]
