name: DrakesGenerators
version: '${project.version}'
main: com.drakescraft.suites.generators.DrakesGeneratorsPlugin
api-version: '1.21'
author: DrakesCraft-Labs
description: Mega-Suite de Matriz Energetica, Reactores Nucleares/Solares y Generacion Cuantica.
depend: [DrakesCore]
