name: DrakesMultiverse
version: '${project.version}'
main: com.drakescraft.suites.multiverse.DrakesMultiversePlugin
api-version: '${plugin.api.version}'
author: Chagui68
authors: [Chagui68, JackStar6677-1]
description: Suite Multiverse oficial creada por Chagui68 (MultiverseCreatures y MultiverseNets).
softdepend: [DrakesCore, DrakesCombat, DrakesTech, DrakesBosses, Slimefun]

commands:
  mvnets:
    description: Comando principal de MultiverseNets.
    usage: /mvnets [help|info|devices|give|doctor|stats|reload]
    aliases: [mvn]
    permission: multiversenets.use

permissions:
  multiversenets.use:
    description: Permite usar el comando base /mvnets.
    default: true
  multiversenets.admin:
    description: Acceso a administracion de redes (give, doctor, stats, reload).
    default: op
    children:
      multiversenets.use: true
